// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using System.Collections.Generic;

public partial class Initial : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "EmploymentPositions",
            columns: table => new
            {
                Id = table.Column<int>(nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                BaseSalary = table.Column<decimal>(nullable: false),
                Title = table.Column<string>(nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_EmploymentPositions", x => x.Id);
            });

        migrationBuilder.Sql(@"
            INSERT INTO EmploymentPositions (Title, BaseSalary)
                VALUES ( 'Software Engineer I', 68425.00 );
            INSERT INTO EmploymentPositions (Title, BaseSalary)
                VALUES ( 'Software Engineer II', 88117.00 );
            INSERT INTO EmploymentPositions (Title, BaseSalary)
                VALUES ( 'Software Engineer III', 110148.00 );
            INSERT INTO EmploymentPositions (Title, BaseSalary)
                VALUES ( 'Software Engineer IV', 132090.00 );
            INSERT INTO EmploymentPositions (Title, BaseSalary)
                VALUES ( 'Software Engineer V', 147876.00 );
            INSERT INTO EmploymentPositions (Title, BaseSalary)
                VALUES ( 'Software Engineering Manager', 137267.00 );
            INSERT INTO EmploymentPositions (Title, BaseSalary)
                VALUES ( 'Software Engineering Director', 190633.00 );
            INSERT INTO EmploymentPositions (Title, BaseSalary)
                VALUES ( 'Chief Technology Officer', 242782.00 );
        ");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "EmploymentPositions");
    }
}

[DbContext(typeof(ApplicationDbContext))]
[Migration("20171201161127_Initial")]
partial class Initial
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

        modelBuilder.Entity("EmploymentPosition", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<decimal>("BaseSalary");

                b.Property<string>("Title");

                b.HasKey("Id");

                b.ToTable("EmploymentPositions");
            });
#pragma warning restore 612, 618
    }
}

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

        modelBuilder.Entity("EmploymentPosition", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<decimal>("BaseSalary");

                b.Property<string>("Title");

                b.HasKey("Id");

                b.ToTable("EmploymentPositions");
            });
#pragma warning restore 612, 618
    }
}